#pragma once

#define APPLICATION_NAME				"vk rendering engine"
#define	WIN32_WINDOW_CLASS_NAME			"VK_RENDERING_ENGINE_WINDOW"

#define DEFAULT_WINDOW_WIDTH			1280
#define DEFAULT_WINDOW_HEIGHT			720

#define ENABLE_DEBUG_LAYERS